### ISSUE TITLE
Error after forum update and extension update

### ISSUE THREAD

**Issue by jakubsuchybio** [marttiphpbb/phpbb-ext-customcode#39]
Hi,
I have deleted phpbbroot/store/customcode and also whole extension in phpbbroot/ext/..., then I uploaded your 1.1.0 version and after enabling in ACP and therefore using phpbb 3.1.6 and customcode 1.1.0 gives me this error:

```
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "../../../../../../store/customcode/overall_header_head_append.html" (looked into: ./styles/pbtech template, ./styles/pbtech/theme, ./styles/prosilver/template, ./styles/prosilver/theme) in "@marttiphpbb_customcode/event/overall_header_head_append.html" at line 5.' in /data/web/virtuals/93680/virtual/www/domains/ezpz.cz/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:195 Stack trace: 
#0 /data/web/virtuals/93680/virtual/www/domains/ezpz.cz/phpbb/template/twig/loader.php(107): Twig_Loader_Filesystem->findTemplate('../../../../../...') 
#1 /data/web/virtuals/93680/virtual/www/domains/ezpz.cz/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(138): phpbb\template\twig\loader->findTemplate('../../../../../...') 
#2 /data/web/virtuals/93680/virtual/www/domains/ezpz.cz/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Filesystem->getCacheKey('../../../../../...') 
#3 /data/web/virtuals/93680/virtual/www/domains/ezpz.cz/vendor/twig/twig/ in /data/web/virtuals/93680/virtual/www/domains/ezpz.cz/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 195
```

Thanks.
Regards Jacob.

**Comment by marttiphpbb** [comment]
The extension is not compatible with phpBB anymore from version 3.1.6 
See the topic: https://www.phpbb.com/community/viewtopic.php?f=456&t=2275361

**Comment by marttiphpbb** [comment]
The issue has been solved and development will continue for phpBB 3.2.1+ and PHP7+
